map_type:             costmap
obstacle_range: 5.5
raytrace_range: 6.0
transform_tolerance:  0.5
#footprint:            [[-0.056, -0.02045], [-0.0106,0.02045], [0.0524, 0.01915], [0.0524, -0.01915]]
footprint:            [[-0.106, -0.1045], [-0.106,0.1045], [0.524, 0.1015], [0.524, -0.1015]]
footprint_padding: 0.00
#robot_radius:        0.2 
inflation_radius:     0.01
observation_sources:  laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /laser_scan, marking: true, clearing: true}
