local_costmap:
   global_frame:      odom
   robot_base_frame:  base_footprint
   update_frequency:  10.0
   publish_frequency: 2.0
   width:             1.0
   height:            1.0
   resolution:        0.005
   static_map:        false
   rolling_window:    true
