
joint_state_controller:
 type: "joint_state_controller/JointStateController"
 publish_rate: 50
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: Claw_Left_J
  pid: {p: 50.0, i: 0.01, d: 10.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: Claw_Right_J
  pid: {p: 50.0, i: 0.01, d: 10.0}
# joint3_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: LF_Wheel_Cont
#   pid: {p: 50.0, i: 0.01, d: 10.0}
# joint4_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: LB_Wheel_Cont
#   pid: {p: 50.0, i: 0.01, d: 10.0}
# joint5_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: RF_Wheel_Cont
#   pid: {p: 50.0, i: 0.01, d: 10.0}
# joint6_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: RB_Wheel_Cont
#   pid: {p: 50.0, i: 0.01, d: 10.0}

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['LF_Wheel_Cont', 'LB_Wheel_Cont']
  right_wheel: ['RF_Wheel_Cont', 'RB_Wheel_Cont']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 10.0
  velocity_rolling_window_size: 2

  # Base frame_id
  base_frame_id: base_footprint

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false
  wheel_separation : 0.210
  wheel_radius : 0.065
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 10.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2